# Specify defaults for testing
PVER = 2.6
PREFIX = /usr
PYTHON = $(PREFIX)/bin/python$(PVER)
PYTHON_CONFIG = $(PYTHON)-config
INSTALL_DIR = $(PREFIX)/lib/python$(PVER)/site-packages
SCRIPT_DIR = $(PREFIX)/bin
MODULEVER = 0.0
ASCIIDOC = asciidoc

# Override with any release info
-include $(TOP)/Makefile.private
